### ISSUE TITLE
Typos in CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Vovka1759** [atapas/js-keyevents-demo#13]
**Describe the bug**
There are some typos in CODE_OF_CONDUCT.md

**To Reproduce**
1. Go to CODE_OF_CONDUCT.md
2. Scroll through the file
3. See some typos

**Expected behavior**
All typos, grammatical, and syntax errors must be corrected

**Comment by saloni137** [comment]
@atapas please assign this to me.

**Comment by atapas** [comment]
We are using the standard CODE_OF_CONDUCT text provided by GitHub as part of the check list. I don;t think, any changes required.
