### ISSUE TITLE
Scroll to Top

### ISSUE THREAD

**Issue by Jony-Jas** [atapas/js-keyevents-demo#16]
When too many keyevents are registered, It takes the user a long time to move to top. 
So, I think we can put a scroll to top button.

**Comment by prateekch33** [comment]
@atapas Please assign this to me

**Comment by Jony-Jas** [comment]
i too need it 🥺

**Comment by atapas** [comment]
Assigned based on @Jony-Jas created the issue but if you both want to work together, go ahead. I can assign to you both. Thanks!
