### ISSUE TITLE
Improved the content in CODE_OF_CONDUCT.md 

### ISSUE THREAD

**Issue by Akshra2020** [atapas/js-keyevents-demo#23]
**Describe the bug**
improve the content in CODE_OF_CONDUCT.md

**Comment by Akshra2020** [comment]
Sir I  have already made a pull request regarding this #17

**Comment by atapas** [comment]
We are using the standard CODE_OF_CONDUCT text provided by GitHub as part of the check list. I don;t think, any changes required.

**Comment by Akshra2020** [comment]
Good evening sir
Sir I have fixed the typos and some grammatical errors
Kindly please check that . If it's not appropriate or if it's not required
exclude it
Thank you
